### ISSUE TITLE
IDE: Comment on first line within `TYPE` block should be indented

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#25]
Comments placed in the first lines inside a `TYPE` block should be indented to match the definitions.
See picture below for example:

![image](https://user-images.githubusercontent.com/142650/35094087-2c8efe4c-fc3c-11e7-85c7-074aa37c8f3c.png)

**Comment by chronokitsune3233** [comment]
I have some reservations about this simply due to the fact that I write comments like this:

```BlitzBasic
' This is a comment
' about the use of the
' foo type in general.
TYPE foo
    ' This is a comment
    ' about how fieldA
    ' is used.
    fieldA AS STRING * 10
    ' Same idea for fieldB.
    fieldB AS INTEGER
END TYPE
```

In addition, it differs from the formatting of comments inside other blocks like `IF...END IF` and `FOR...NEXT`. An exception for `TYPE...END TYPE` blocks may or may not be feasible, but even if it is, I would rather QB64 allow me to comment as I like. I can always indent/unindent the comment as necessary.

**Comment by Kroc** [comment]
You misunderstand -- this is how QB64 formats your given text:

![image](https://user-images.githubusercontent.com/142650/35274405-e435d304-0033-11e8-9821-d975a832bb5c.png)

The first set of comments _inside_ a `TYPE` definition are always un-indented, when they should really be indented.

**Comment by FellippeHeitor** [comment]
I'm on it. Thanks for reporting.

**Comment by FellippeHeitor** [comment]
The development build now contains a fix for the misalignment of the first comment lines of a TYPE block. The issue also affected DECLARE LIBRARY blocks and has also been fixed on that front.
