### ISSUE TITLE
Allow `_CONTINUE` to work with nested-loops

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#26]
`_CONTINUE` works only with the current loop it is within. Many languages provide a parameter to specify the depth the statement should loop on. I.e.:

```
FOR x% = 1 TO 10
    FOR y% = 1 TO 10
        'when y reaches five, skip to the next x%, NOT the next y%
        IF y% = 5 THEN _CONTINUE 2
    NEXT y%
NEXT x%
```

The ability to specify the `FOR` variable instead of a depth would be appreciated:

```
FOR x% = 1 TO 10
    FOR y% = 1 TO 10
        'when y reaches five, skip to the next x%, NOT the next y%
        IF y% = 5 THEN _CONTINUE x%
    NEXT y%
NEXT x%
```

NB: Since the addition of `_CONTINUE` to the language, the `FOR ... NEXT`, `DO ... LOOP` etc. pages need it adding to their documentation.

**Comment by chronokitsune3233** [comment]
`_CONTINUE <count>` would be a bit unintuitive as you'd need to determine how many levels to go up (and if you added another loop later, you might need to change that value).

`_CONTINUE <variable>` is perhaps a better option, but it only works with `FOR` loops, which is not ideal.

As a workaround, QB64 has another way to achieve what you want&mdash;a method that should be relatively familiar to someone who has needed such functionality in a language supporting a `GOTO` equivalent in some form that doesn't provide the feature you are requesting:

```BlitzBasic
FOR x% = 1 TO 3
    PRINT "X START"; x%
    FOR y% = 1 TO 5
        PRINT "Y START"; y%
        IF y% = 3 THEN GOTO xLoopEnd
        PRINT "Y END"
    NEXT y%
    PRINT "X END"; x%
xLoopEnd:
NEXT x%

' Line-numbered alternative.
FOR x% = 1 TO 3
    PRINT "X START"; x%
    FOR y% = 1 TO 5
        PRINT "Y START"; y%
        IF y% = 3 THEN GOTO 99
        PRINT "Y END"
    NEXT y%
    PRINT "X END"; x%
99 NEXT x%
```

In my opinion, `_CONTINUE` in its current form is a convenient shortcut that provides behavior equivalent to this:

```BlitzBasic
FOR x% = 1 TO 3
    PRINT "X START"; x%
    FOR y% = 1 TO 5
        PRINT "Y START"; y%
        IF y% = 3 THEN GOTO yLoopEnd
        PRINT "Y END"
        yLoopEnd:
    NEXT y%
    PRINT "X END"; x%
NEXT x%
```

The same argument could be made for `EXIT {FOR|WHILE|DO} [{line-label|line-number}]`, but the same argument against the feature could be made.

What does make sense, however, is doing this:

```BlitzBasic
xLoop:
FOR x% = 1 TO 3
    PRINT "X START"; x%
    FOR y% = 1 TO 5
        PRINT "Y START"; y%
        ' Alternatively, EXIT FOR xLoop
        IF y% = 3 THEN _CONTINUE xLoop
        PRINT "Y END"
    NEXT y%
    PRINT "X END"; x%
NEXT x%

' Line-numbered alternative
99 FOR x% = 1 TO 3
    PRINT "X START"; x%
    FOR y% = 1 TO 5
        PRINT "Y START"; y%
        ' Alternatively, EXIT FOR 99
        IF y% = 3 THEN _CONTINUE 99
        PRINT "Y END"
    NEXT y%
    PRINT "X END"; x%
NEXT x%
```

This way, you know which loop you're continuing/exiting because it's clearly labeled; the `GOTO` method also works, but it is arguably less intuitive.

**Comment by FellippeHeitor** [comment]
Since GOTO is a traditional structure in BASIC, _CONTINUE was implemented was a shortcut borrowing directly from C for the sake of simplicity; we have agreed internally that for other cases we will keep it as is, otherwise _CONTINUE would become a mere alias for GOTO after all. However, we do welcome any pull requests eventually made in that direction
