### ISSUE TITLE
Ability to open QBX 7.1 binary format sourcefiles

### ISSUE THREAD

**Issue by figge4** [Galleondragon/qb64#34]
It would be great if I could open my old .BAS sourcefiles, apperantly created with this format. Today it tells me it is not supported.

**Comment by FellippeHeitor** [comment]
We added support for QuickBASIC 4.5 binary format in version 1.2 and the minimal ability to recognize a file is in QBX 7.1 and VBDOS format and at least inform the user they aren't supported.

The converter we have was written by qarnos, who did a thorough investigation into the format to come up with his brilliant code.

However, at this point, we have lost contact with qarnos and don't know whether he came up with an extended converter for other binary formats or not.

While I also believe this would be a great addition, bear in mind that QBX files will very likely contain instructions and functions that are not implemented in QB64, since we strive to increase compatibility with QBasic/QuickBASIC 4.5.

Of course that doesn't mean you shouldn't try your sources in QB64: the adaptation for them to work may be minimal after all.

Do you have too many files to convert? I know a friend of a friend who has a copy of QBX in DOSBox and I could aid you in the task if your sources aren't top secret and you are willing to send them to me (fellippe at qb64.org)
